AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  emotions-api

  Sample SAM Template for emotions-api

Globals:
  Function:
    Timeout: 3
  Api:
    BinaryMediaTypes:
      - "*~1*"

Resources:
  EmotionsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambdaHandler
      Runtime: nodejs8.10
      Policies:
        - AmazonRekognitionReadOnlyAccess
      Events:
        HelloWorld:
          Type: Api
          Properties:
            Path: /emotions
            Method: post

Outputs:
  Api:
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/"
